devices:
  - id: 0
    type: "net"
    mmio_addr: 0xa003e00
    data_plane: virtio
    tap_name: "tap0"
    mac_addr: "52:54:00:12:34:56"
  - id: 1
    type: "net"
    mmio_addr: 0xa003e00
    data_plane: virtio
    tap_name: "tap1"
    mac_addr: "52:54:00:12:34:57"