devices:
    # --- Common ---
  - id: 0
    type: "vsock"
    shmem_addr: 0x80000000
    shmem_size: 0x01000000
    shmem_path: "/dev/baoipc0"
    mmio_addr: 0xa003e00
    irq: 47
    data_plane: vhost
    # --- Vsock specific ---
    guest_cid: 3
    # -----------------------------