devices:
  - id: 0
    type: "net"
    shmem_addr: 0x80000000
    shmem_size: 0x01000000
    shmem_path: "/dev/baoipc1"
    mmio_addr: 0xa003e00
    irq: 47
    data_plane: virtio
    tap_name: "tap0"
    mac_addr: "52:54:00:12:34:56"