devices:
  - id: 1
    type: "net"
    shmem_addr: 0x81000000
    shmem_size: 0x01000000
    shmem_path: "/dev/baoipc2"
    mmio_addr: 0xa003e00
    irq: 47
    data_plane: virtio
    tap_name: "tap1"
    mac_addr: "52:54:00:12:34:57"